meta_product_name: "BioMap"
meta_title: "BioMap - Trouve les producteurs locaux & bio"
meta_description: "Trouve les producteurs locaux & bio"
meta_image: "BiomapLogo.png" # should exist in `app/assets/images/`
